<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,maximum-scale=1">
<meta name="theme-color" content="#000000"><meta name="color-scheme" content="dark">
<meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="XASS">
<link rel="manifest" href="/manifest.webmanifest"><link rel="apple-touch-icon" href="/assets/xass-app-icon-192.png">
<title>XASS</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
:root{--bg:#000;--surface:#090b0f;--surface2:#0e1117;--line:#242933;--text:#f5f7fb;--muted:#8c94a2;--blue:#4a7dff;--violet:#7f65ff;--green:#56dd91;--amber:#f0bd6b;--red:#ff7480}
*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}html{background:#000;scroll-behavior:smooth}body{min-height:100vh;background:#000;color:var(--text);font:14px/1.55 Manrope,"Segoe UI",sans-serif;padding-bottom:calc(92px + env(safe-area-inset-bottom));overflow-x:hidden}button,input,textarea,select{font:inherit}button{cursor:pointer}.wrap{width:min(760px,100%);margin:auto;padding:0 18px 32px}.head{height:86px;display:flex;align-items:center;border-bottom:1px solid var(--line);position:relative}.brand{display:flex;align-items:center;gap:11px;font-size:30px;font-weight:600;letter-spacing:-1.7px}.brand img{width:33px;height:33px;object-fit:contain}.head-state{margin-left:auto;color:var(--muted);font-size:11px;display:flex;align-items:center;gap:8px}.dot{width:7px;height:7px;border-radius:50%;background:var(--amber)}.dot.ok{background:var(--green)}.dot.bad{background:var(--red)}
.view{display:none}.view.on{display:block;animation:enter .2s ease both}@keyframes enter{from{opacity:.3;transform:translateY(5px)}to{opacity:1;transform:none}}.intro{padding:32px 0 28px;border-bottom:1px solid var(--line)}.eyebrow{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.12em}.intro h1{font-size:clamp(34px,8vw,58px);font-weight:500;letter-spacing:-.055em;line-height:1.02;margin:11px 0 13px}.intro p{max-width:560px;color:#b2b8c2}.section{padding:28px 0;border-bottom:1px solid var(--line)}.section:last-child{border-bottom:0}.section-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:16px}.section-title{font-size:23px;line-height:1.12;font-weight:500;letter-spacing:-.035em}.section-note{color:var(--muted);font-size:10px}.line-list{border-top:1px solid var(--line)}.row{display:flex;gap:14px;align-items:center;min-height:66px;padding:12px 0;border-bottom:1px solid var(--line)}.row-main{min-width:0;flex:1}.row-title{font-weight:600}.row-sub{color:var(--muted);font-size:11px;margin-top:3px;word-break:break-word}.row-side{font-size:11px;color:var(--muted);text-align:right}.row-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.icon{width:28px;height:28px;color:var(--blue);flex:0 0 auto}.metrics{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.metric{padding:17px 14px;border-right:1px solid var(--line)}.metric:last-child{border:0}.metric-name{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.09em}.metric-value{font-size:28px;letter-spacing:-.04em;margin-top:7px}.metric-bar{height:2px;background:#1c2028;margin-top:12px}.metric-bar i{display:block;height:100%;background:var(--blue)}
.feature{border:1px solid #293752;background:radial-gradient(circle at 0 0,rgba(51,108,255,.18),transparent 55%),var(--surface);padding:18px}.feature-grid{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:center}.feature-mark{width:74px;height:74px;object-fit:contain}.weather-value{font-size:31px;letter-spacing:-.04em;margin-top:7px}.weather-detail{color:var(--muted);margin-top:8px}.seg{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line);margin:16px 0}.seg button{border:0;border-right:1px solid var(--line);background:transparent;color:var(--muted);padding:12px 8px}.seg button:last-child{border:0}.seg button.on{background:#121722;color:#fff;box-shadow:inset 0 -2px var(--blue)}.search{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px}.input{width:100%;background:var(--surface);border:1px solid var(--line);color:var(--text);padding:12px 13px;outline:none;border-radius:0}.input:focus{border-color:#4b6fa9}textarea.input{min-height:152px;line-height:1.65;resize:vertical;overflow:auto}.field{margin-top:14px}.label{display:flex;justify-content:space-between;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.09em;margin-bottom:7px}.btn{border:1px solid var(--line);background:var(--surface);color:var(--text);min-height:42px;padding:9px 14px;font-size:11px;font-weight:600}.btn.primary{background:var(--blue);border-color:var(--blue);color:white}.btn.blue{border-color:#365da9;color:#84adff}.btn.danger{border-color:#68353b;color:#ff9ca5;background:#14090b}.btn:disabled{opacity:.42;cursor:default}.btn:active{transform:translateY(1px)}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.toolbar .btn{flex:1}.links{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.links a{border:1px solid var(--line);color:#c6d5ff;text-decoration:none;padding:9px 12px;font-size:11px}.music-result{display:none;margin-top:18px;padding-top:18px;border-top:1px solid var(--line)}.track{display:grid;grid-template-columns:58px minmax(0,1fr);gap:14px;align-items:center}.track-art{width:58px;height:58px;background:var(--surface2);object-fit:cover}.track-title{font-size:17px;font-weight:600}.track-meta{color:var(--muted);font-size:11px;margin-top:3px}
.toggle{width:46px;height:26px;border:1px solid var(--line);background:#11151c;border-radius:99px;position:relative;flex:0 0 auto}.toggle:after{content:"";position:absolute;width:20px;height:20px;left:2px;top:2px;background:#c8ced8;border-radius:50%;transition:.18s}.toggle.on{background:var(--blue);border-color:var(--blue)}.toggle.on:after{transform:translateX(20px);background:#fff}.status{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--green)}.status.off{color:var(--red)}.device-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.warning{color:var(--amber);font-size:10px;margin-top:5px}.install-row{display:grid;grid-template-columns:56px minmax(0,1fr);gap:14px;align-items:center}.install-row img{width:56px;height:56px}.pair-code{font:600 28px/1.2 "Cascadia Mono",Consolas,monospace;letter-spacing:4px;color:#8badff;margin:16px 0}.mono{font-family:"Cascadia Mono",Consolas,monospace}.disclosure{border-top:1px solid var(--line)}.disclosure details{border-bottom:1px solid var(--line)}.disclosure summary{list-style:none;display:flex;align-items:center;justify-content:space-between;padding:17px 0;font-weight:600}.disclosure summary::-webkit-details-marker{display:none}.disclosure summary:after{content:"+";color:var(--muted);font-size:20px}.disclosure details[open] summary:after{content:"−"}.detail-body{padding:0 0 18px}.log{padding:11px 0;border-bottom:1px solid var(--line)}.log:last-child{border:0}.log-meta{font-size:10px;color:var(--muted);display:flex;justify-content:space-between;gap:10px}.log-text{font-size:12px;margin-top:5px}.quote{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)}.quote:last-child{border:0}.empty{color:var(--muted);padding:15px 0;font-size:12px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{grid-column:1/-1}.project{padding:14px 0;border-bottom:1px solid var(--line)}.project:first-child{border-top:1px solid var(--line)}.project-head{display:flex;justify-content:space-between;gap:14px}.project-name{font-weight:600}.project-desc{color:var(--muted);font-size:11px;margin-top:4px}.project-form{display:none;margin-top:18px;padding-top:4px}.muted{color:var(--muted)}.danger-text{color:var(--red)}
.tabs{position:fixed;z-index:30;left:0;right:0;bottom:0;background:rgba(0,0,0,.95);border-top:1px solid var(--line);padding:5px 6px calc(5px + env(safe-area-inset-bottom));backdrop-filter:blur(18px)}.tabs-inner{width:min(760px,100%);margin:auto;display:grid;grid-template-columns:repeat(5,1fr)}.tab{border:0;background:transparent;color:#747b88;min-height:61px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:9px}.tab svg{width:21px;height:21px}.tab.on{color:#7ba4ff}.toast{position:fixed;z-index:90;left:50%;bottom:90px;transform:translate(-50%,15px);opacity:0;pointer-events:none;background:#141820;border:1px solid #343b48;padding:10px 14px;max-width:90%;font-size:12px;transition:.2s}.toast.show{opacity:1;transform:translate(-50%,0)}.screen{position:fixed;z-index:80;inset:0;background:#000;display:flex;align-items:center;justify-content:center;padding:28px}.loader{display:flex;align-items:center;gap:12px;color:var(--muted)}.spin{width:25px;height:25px;border:2px solid var(--line);border-top-color:var(--blue);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.login{display:none;text-align:center;width:min(390px,100%)}.login img{width:142px;height:142px;object-fit:contain;margin-bottom:18px}.login h1{font-size:34px;font-weight:500;letter-spacing:-.05em}.login p{color:var(--muted);margin:10px 0 22px}.widget{min-height:48px;display:flex;justify-content:center}.ios-help{margin-top:20px;border-top:1px solid var(--line);padding-top:16px;color:#b4bac4;font-size:11px}.deny{display:none;text-align:center;width:min(390px,100%)}.deny h2{font-size:26px;margin-bottom:9px}.deny p{color:var(--muted);margin-bottom:18px}
@media(max-width:520px){.wrap{padding-left:15px;padding-right:15px}.head{height:74px}.brand{font-size:27px}.brand img{width:29px;height:29px}.metrics{grid-template-columns:1fr}.metric{display:grid;grid-template-columns:74px 1fr;align-items:center;border-right:0;border-bottom:1px solid var(--line)}.metric:last-child{border:0}.metric-value{font-size:23px;margin:0;text-align:right}.metric-bar{grid-column:1/-1}.section{padding:24px 0}.section-title{font-size:21px}.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.row{align-items:flex-start}.row-actions{width:100%;justify-content:flex-start}.feature-grid{grid-template-columns:1fr auto}.tabs .tab{font-size:8px}.search{grid-template-columns:1fr}.search .btn{width:100%}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
</style>
</head>
<body>
<div class="screen" id="gate"><div class="loader" id="loader"><div class="spin"></div><span>Подключение к XASS…</span></div><div class="login" id="login"><img src="/assets/xass-app-icon-512.png" alt="XASS"><h1>XASS</h1><p>Войдите Telegram-аккаунтом владельца, чтобы управлять системой с iPhone и рабочего стола.</p><div class="widget" id="telegramWidget"></div><div class="ios-help">На iPhone после входа: «Поделиться» → «На экран Домой». XASS откроется как отдельное приложение.</div></div><div class="deny" id="deny"><h2>Нет доступа</h2><p id="denyText">Не удалось подключиться.</p><button class="btn" id="retryBtn">Повторить</button></div></div>
<div class="toast" id="toast"></div>
<main class="wrap" id="app" hidden>
 <header class="head"><div class="brand"><img src="/assets/xass-app-icon-192.png" alt=""><span>XASS</span></div><div class="head-state"><span class="dot" id="headDot"></span><span id="headStatus">Подключение</span></div></header>

 <section class="view on" id="view-home">
  <div class="intro"><div class="eyebrow">Личный центр управления</div><h1 id="helloTitle">Система в сети.</h1><p>Сервер, устройства, музыка и сайт — в одном спокойном интерфейсе.</p></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Состояние</h2><span class="section-note" id="appVersion">—</span></div><div class="metrics" id="homeMetrics"></div></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Устройства</h2><button class="btn" data-view="tools">Управление</button></div><div class="line-list" id="homeDevices"></div></div>
  <div class="section"><div class="feature feature-grid"><div><div class="eyebrow">Сейчас играет · <span id="homeSource">—</span></div><div class="weather-value" id="homeTrack">Нет свежих данных</div><div class="weather-detail" id="homeTrackHint">Музыкальный поиск доступен в отдельном разделе.</div></div><img class="feature-mark" src="/assets/xass-app-icon-192.png" alt=""></div></div>
 </section>

 <section class="view" id="view-music">
  <div class="intro"><div class="eyebrow">Музыка</div><h1>Трек не должен теряться.</h1><p>Выберите источник, найдите текущую композицию и откройте её в нужном сервисе.</p></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Источник «Сейчас играет»</h2><span class="section-note" id="musicFreshness">LIVE</span></div><div class="seg" id="sourceSeg"><button data-source="pc_agent">ПК</button><button data-source="iphone">iPhone</button><button data-source="vk">VK</button></div><div class="feature"><div class="eyebrow" id="musicSourceLabel">Источник</div><div class="weather-value" id="musicNow">Нет свежих данных</div><div class="weather-detail" id="musicEmptyHint">Источник пока не прислал трек. Поиск ниже всё равно работает.</div></div></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Найти музыку</h2><span class="section-note">5 сервисов</span></div><div class="search"><input class="input" id="musicInput" placeholder="Исполнитель — трек"><button class="btn primary" id="musicBtn">Найти</button></div><div class="music-result" id="musicResult"><div class="track"><img class="track-art" id="musicArt" alt=""><div><div class="track-title" id="musicTitle"></div><div class="track-meta" id="musicMeta"></div></div></div><div class="links" id="musicLinks"></div></div></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Подключения</h2></div><div class="line-list"><div class="row"><div class="row-main"><div class="row-title">Discord username</div><div class="row-sub">Нужен для статуса активности на сайте.</div></div></div></div><div class="search"><input class="input" id="discordTag" placeholder="username"><button class="btn" id="discordSave">Сохранить</button></div><div class="field"><label class="label"><span>VK App ID</span><span id="vkState">не подключён</span></label><div class="search"><input class="input" id="vkAppId" inputmode="numeric" placeholder="12345678"><button class="btn" id="vkSave">Сохранить</button></div></div><button class="btn blue" id="vkConnect" style="width:100%;margin-top:9px">Подключить ВКонтакте</button></div>
 </section>

 <section class="view" id="view-tools">
  <div class="intro"><div class="eyebrow">Инструменты</div><h1>Управление без потерь.</h1><p>Настройки бота, Windows-агенты, блокировка экрана и обслуживание сервера.</p></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Бот</h2><span class="section-note">OWNER</span></div><div class="line-list"><div class="row"><div class="row-main"><div class="row-title">Сохранение сообщений</div><div class="row-sub" id="saveModeDesc">—</div></div><button class="btn" id="saveModeBtn">Сменить</button></div><div class="row"><div class="row-main"><div class="row-title">Тихие часы</div><div class="row-sub" id="quietDesc">—</div></div><button class="toggle" id="quietToggle" aria-label="Тихие часы"></button></div><div class="row"><div class="row-main"><div class="row-title">Режим «Не в сети»</div><div class="row-sub" id="awayDesc">—</div></div><button class="toggle" id="awayToggle" aria-label="Режим не в сети"></button></div></div><div class="field"><label class="label"><span>Текст автоответа</span><span id="awayCount">0</span></label><textarea class="input" id="awayMessage" maxlength="4000" placeholder="Напишите полный автоответ…"></textarea><button class="btn blue" id="awaySaveBtn" style="width:100%;margin-top:9px">Сохранить автоответ</button></div></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Windows</h2><span class="section-note">AGENT</span></div><div class="install-row"><img src="/assets/xass-app-icon-192.png" alt=""><div><div class="row-title">XASS для Windows</div><div class="row-sub" id="installerMeta">Проверяю установщик…</div></div></div><div class="toolbar" style="margin-top:14px"><button class="btn primary" id="downloadInstallerBtn">Скачать установщик</button><button class="btn" id="pairBtn">Добавить ПК</button></div><div class="feature" id="pairPanel" style="display:none;margin-top:14px"><div class="eyebrow">Одноразовое подключение</div><div class="pair-code" id="pairCode">—</div><input class="input mono" id="pairServerUrl" placeholder="https://server.example"><div class="row-sub" id="pairExpiry"></div><div class="toolbar" style="margin-top:12px"><button class="btn" id="downloadPairBtn">Файл .xass</button><button class="btn" id="copyPairBtn">Копировать</button></div></div><div class="line-list" id="deviceList" style="margin-top:18px"></div></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Сервер</h2><button class="btn" id="refreshBtn">Обновить</button></div><div class="metrics" id="serverMetrics"></div><div class="line-list" id="serviceList" style="margin-top:18px"></div><div class="toolbar" style="margin-top:14px"><button class="btn" id="checkUpdateBtn">Проверить обнову</button><button class="btn primary" id="runUpdateBtn">Обновить сервер</button><button class="btn danger" id="restartServerBtn">Перезапустить</button></div><pre class="row-sub mono" id="updateResult" style="display:none;white-space:pre-wrap;margin-top:12px"></pre></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Данные</h2></div><div class="disclosure"><details><summary>Последние сообщения</summary><div class="detail-body"><button class="btn" id="logsBtn">Обновить 30</button><div id="logList"></div></div></details><details><summary>Цитаты</summary><div class="detail-body"><div class="search"><input class="input" id="quoteInput" placeholder="Новая цитата"><button class="btn" id="quoteAdd">Добавить</button></div><div id="quoteList" style="margin-top:10px"></div></div></details><details><summary>Диагностика</summary><div class="detail-body"><p class="muted">Копия безопасной сводки без токенов и ключей.</p><button class="btn" id="copyDiag" style="margin-top:10px">Копировать диагностику</button></div></details></div></div>
 </section>

 <section class="view" id="view-weather">
  <div class="intro"><div class="eyebrow">Погода</div><h1>Отдельно от контактов.</h1><p>Актуальная сводка живёт в собственном разделе и больше не ломает список ссылок.</p></div><div class="section"><div class="feature"><div class="eyebrow" id="weatherPlace">Погода</div><div class="weather-value" id="weatherMain">Обновляется…</div><div class="weather-detail" id="weatherDetails"></div></div></div>
 </section>

 <section class="view" id="view-site">
  <div class="intro"><div class="eyebrow">Сайт</div><h1>Профиль и проекты.</h1><p>Публичная страница редактируется здесь без захода на сервер.</p></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Профиль</h2><button class="btn" id="openSiteBtn">Открыть сайт</button></div><div class="form-grid"><div class="field"><label class="label">Имя</label><input class="input" id="siteName"></div><div class="field"><label class="label">Username</label><input class="input" id="siteUsername"></div><div class="field full"><label class="label">Заголовок</label><input class="input" id="siteTitle"></div><div class="field full"><label class="label">О себе</label><textarea class="input" id="siteBio"></textarea></div><div class="field"><label class="label">Telegram URL</label><input class="input" id="siteTelegram"></div><div class="field"><label class="label">Avatar URL</label><input class="input" id="siteAvatar"></div><div class="field full"><label class="label">Цитата</label><input class="input" id="siteQuote"></div><div class="field full"><label class="label">Стек через запятую</label><input class="input" id="siteStack"></div><div class="field full"><label class="label">Ссылки: Название | URL</label><textarea class="input" id="siteLinks"></textarea></div></div><button class="btn primary" id="saveProfileBtn" style="width:100%;margin-top:14px">Сохранить профиль</button></div>
  <div class="section"><div class="section-head"><h2 class="section-title">Проекты</h2><button class="btn" id="newProjectBtn">Новый</button></div><div id="projectList"></div><div class="project-form" id="projectForm"><h3 id="projectFormTitle">Новый проект</h3><input type="hidden" id="projectId"><div class="form-grid"><div class="field"><label class="label">Название</label><input class="input" id="projectTitle"></div><div class="field"><label class="label">Статус</label><input class="input" id="projectStatus"></div><div class="field full"><label class="label">Подзаголовок</label><input class="input" id="projectSubtitle"></div><div class="field full"><label class="label">Описание</label><textarea class="input" id="projectDescription"></textarea></div><div class="field full"><label class="label">URL</label><input class="input" id="projectUrl"></div><div class="field"><label class="label">Год с</label><input class="input" id="projectFrom" type="number"></div><div class="field"><label class="label">Год по</label><input class="input" id="projectTo" type="number"></div><div class="field full"><label class="label">Теги</label><input class="input" id="projectTags"></div><div class="field full"><label class="label">Обложка URL</label><input class="input" id="projectCover"></div><label class="row full"><input id="projectFeatured" type="checkbox"> <span>Показывать первым</span></label></div><div class="toolbar"><button class="btn primary" id="saveProjectBtn">Сохранить</button><button class="btn" id="cancelProjectBtn">Отмена</button></div></div></div>
  <div class="section" id="pwaSection"><div class="section-head"><h2 class="section-title">На iPhone</h2></div><p class="muted">Откройте эту страницу в Safari, войдите через Telegram и выберите «Поделиться» → «На экран Домой».</p><button class="btn danger" id="logoutBtn" style="margin-top:14px;display:none">Выйти из Telegram</button></div>
 </section>
</main>

<nav class="tabs" id="tabs" hidden><div class="tabs-inner">
 <button class="tab on" data-view="home"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m3 11 9-8 9 8v9H3z"/><path d="M9 20v-6h6v6"/></svg>Главная</button>
 <button class="tab" data-view="music"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/></svg>Музыка</button>
 <button class="tab" data-view="tools"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 3v18M3 12h18"/><circle cx="12" cy="12" r="8"/></svg>Инструменты</button>
 <button class="tab" data-view="weather"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M7 17h10a4 4 0 0 0 0-8 6 6 0 0 0-11-1A4.5 4.5 0 0 0 7 17Z"/></svg>Погода</button>
 <button class="tab" data-view="site"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>Сайт</button>
</div></nav>
<script>
(()=>{'use strict';
const $=id=>document.getElementById(id), tg=window.Telegram?.WebApp, initData=tg?.initData||'', demo=new URLSearchParams(location.search).get('demo')==='1';
const state={boot:null,site:null,owner:false,pwa:!initData,connection:null};
if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#000000');tg.setBackgroundColor('#000000')}catch(e){}}
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function haptic(kind='light'){try{tg?.HapticFeedback?.impactOccurred(kind)}catch(e){}}
function ask(text,yes){if(tg?.showConfirm)tg.showConfirm(text,yes);else yes(confirm(text))}
function demoBoot(){return{ok:true,app_version:'0.7.0',user:{id:42,first_name:'Владелец',is_owner:true},metrics:{cpu_percent:18,ram_used_percent:43,disk_used_percent:61},status:{now_listening:'M83 — Midnight City',now_source:'pc_agent',now_source_label:'PC',weather:'Москва: 24.1°C, малооблачно, ощущается как 25.2°C, ветер 2.7 м/с',discord_tag:'owner',vk_connected:false},settings:{save_mode:'SAVE_FULL',quiet_enabled:true,away_enabled:false,away_message:'Привет, я сейчас не в сети. Сообщение сохранено — отвечу, как смогу.'},sources:[{source_name:'Домашний ПК',source_type:'PC_AGENT',is_online:true,last_seen_at:new Date().toISOString(),agent_version:'0.7.0',last_payload:{platform:'Windows'}}],services:{nginx:'active',postgresql:'active'},windows_installer:{available:true,version:'0.7.0',size:73400320,file_name:'XASS-Setup.exe'},vk_app_id:''}}
function demoApi(path,opts={}){let data={ok:true};if(path==='bootstrap')data=demoBoot();else if(path.startsWith('music'))data={ok:true,artist:'M83',title:'Midnight City',album:'Hurry Up, We’re Dreaming',artwork_url:'',links:{VK:'#',Shazam:'#','Apple Music':'#',Google:'#','Yandex Music':'#'}};else if(path==='site')data={ok:true,can_edit:true,public_url:'/profile.php',profile:{name:'XASS',username:'lucifervalter',title:'Системы, которые остаются живыми.',bio:'Собираю сервисы и интерфейсы.',telegram_url:'https://t.me/lucifervalter',avatar_url:'',quote:'Делаю сложное спокойным.',stack:['Python','FastAPI'],links:[{label:'GitHub',url:'https://github.com/lucifervalter-a11y'}]},projects:[{id:'xass',title:'XASS',status:'live',description:'Личный центр управления.',years:{from:2025,to:2026},tags:['Python'],cover:{src:''}}]};else if(path.startsWith('logs'))data={ok:true,logs:[{chat_title:'XASS',direction:'system',text:'Heartbeat получен',date:new Date().toISOString()}]};else if(path==='quotes')data={ok:true,quotes:[{id:'1',text:'Делаем просто и надёжно.'}]};else if(path==='agents/pair-code')data={ok:true,code:'XASS2048',ttl_minutes:15,server_url:location.origin,connection:{format:'xass-connect',version:1,server_url:location.origin,pair_code:'XASS2048',auto_update:true}};else if(path==='update-status')data={ok:true,has_updates:true,commits:[{subject:'UI and PWA'}]};else if(path==='run-update'||path==='restart')data={ok:true,restart_scheduled:false,steps:['Готово']};else if(path.includes('/commands'))data={ok:true,command:{status:'pending'}};else if(path==='setting')data={ok:true,settings:state.boot.settings,status:state.boot.status};else if(path==='vk-url')data={ok:true,url:'#'};return Promise.resolve({status:200,data})}
function api(path,opts={}){if(demo)return demoApi(path,opts);const headers=new Headers(opts.headers||{});if(initData)headers.set('X-Telegram-Init-Data',initData);if(opts.body&&typeof opts.body!=='string'){headers.set('Content-Type','application/json');opts.body=JSON.stringify(opts.body)}return fetch('/proxy.php?_p='+encodeURIComponent('/api/mini/'+path),{...opts,headers,credentials:'include'}).then(async r=>{const env=await r.json();let data=null;try{data=JSON.parse(env._b||'')}catch(e){}return{status:Number(env._s||r.status),data,raw:env._b||''}})}
async function pwaApi(path,opts={}){const headers=new Headers(opts.headers||{});if(opts.body&&typeof opts.body!=='string'){headers.set('Content-Type','application/json');opts.body=JSON.stringify(opts.body)}const response=await fetch('/proxy.php?_passthrough=1&_p='+encodeURIComponent('/api/pwa/'+path),{...opts,headers,credentials:'include'});let data=null;try{data=await response.json()}catch(e){}return{status:Number(response.headers.get('X-XASS-Status')||response.status),data}}
function metricHtml(m={}){return[['CPU',m.cpu_percent],['Память',m.ram_used_percent],['Диск',m.disk_used_percent]].map(([name,v])=>{v=Math.max(0,Math.min(100,Number(v)||0));return'<div class="metric"><div class="metric-name">'+name+'</div><div class="metric-value">'+Math.round(v)+'%</div><div class="metric-bar"><i style="width:'+v+'%"></i></div></div>'}).join('')}
function age(iso){if(!iso)return'нет данных';const sec=Math.max(0,(Date.now()-new Date(iso).getTime())/1000);return sec<60?Math.round(sec)+' сек назад':sec<3600?Math.floor(sec/60)+' мин назад':Math.floor(sec/3600)+' ч назад'}
function versionAtLeast(value,wanted){const a=String(value||'0').split('.').map(Number),b=wanted.split('.').map(Number);for(let i=0;i<3;i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return true}
function isPc(item){return /pc|windows/i.test(String(item.source_type||'')+' '+String(item.last_payload?.platform||''))}
function deviceHtml(list,actions=false){return(list||[]).map(item=>{const pc=isPc(item),old=pc&&!versionAtLeast(item.agent_version,'0.6.0');return'<div class="row"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">'+(pc?'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>':'<rect x="4" y="3" width="16" height="7" rx="2"/><rect x="4" y="14" width="16" height="7" rx="2"/>')+'</svg><div class="row-main"><div class="row-title">'+esc(item.source_name)+'</div><div class="row-sub">v'+esc(item.agent_version||'0.0.0')+' · '+age(item.last_seen_at)+'</div>'+(old?'<div class="warning">Для блокировки установите свежий агент.</div>':'')+(actions&&state.owner?'<div class="device-actions"><button class="btn blue agent-command" data-source="'+esc(item.source_name)+'" data-command="update">Обновить</button><button class="btn agent-command" data-source="'+esc(item.source_name)+'" data-command="restart">Перезапустить</button>'+(pc?'<button class="btn danger agent-command" data-source="'+esc(item.source_name)+'" data-command="lock">Заблокировать экран</button>':'')+'</div>':'')+'</div><span class="status '+(item.is_online?'':'off')+'">'+(item.is_online?'В сети':'Offline')+'</span></div>'}).join('')||'<div class="empty">Устройства ещё не подключены.</div>'}
function renderSettings(s={}){const modes={SAVE_OFF:'Выключено',SAVE_BASIC:'Базовый',SAVE_FULL:'Полный + медиа',SAVE_PRIVATE_ONLY:'Только личные',SAVE_GROUPS_ONLY:'Только группы'};$('saveModeDesc').textContent=modes[s.save_mode]||s.save_mode||'—';$('quietToggle').classList.toggle('on',!!s.quiet_enabled);$('quietDesc').textContent=s.quiet_enabled?'Включены':'Выключены';$('awayToggle').classList.toggle('on',!!s.away_enabled);$('awayDesc').textContent=s.away_enabled?'Автоответ включён':'Выключен';$('awayMessage').value=s.away_message||'';updateAwayCount()}
function renderMusic(status={}){const source=status.now_source||'pc_agent',raw=String(status.now_listening||'').trim(),stale=!raw||/нет (свежих )?данных|ничего не играет/i.test(raw);document.querySelectorAll('#sourceSeg button').forEach(b=>b.classList.toggle('on',b.dataset.source===source));$('homeSource').textContent=status.now_source_label||source;$('musicSourceLabel').textContent='Источник · '+(status.now_source_label||source);$('homeTrack').textContent=stale?'Нет свежих данных':raw;$('musicNow').textContent=stale?'Нет свежих данных':raw;$('homeTrackHint').textContent=stale?'Выберите ПК, iPhone или VK — поиск музыки всё равно доступен.':'Нажмите раздел «Музыка», чтобы открыть трек в сервисах.';$('musicEmptyHint').textContent=stale?'Источник пока не прислал трек. Введите название ниже или переключите источник.':'Можно найти этот трек во всех сервисах ниже.';$('musicInput').value=stale?'':raw;$('discordTag').value=status.discord_tag||'';$('vkState').textContent=status.vk_connected?'подключён':'не подключён'}
function renderWeather(text=''){const parts=String(text||'').split(',').map(x=>x.trim()).filter(Boolean),first=parts.shift()||'Погода обновляется…';let place='Погода',main=first;if(first.includes(':')){const cut=first.indexOf(':');place='Погода · '+first.slice(0,cut);main=first.slice(cut+1).trim()}$('weatherPlace').textContent=place;$('weatherMain').textContent=main;$('weatherDetails').textContent=parts.join(' · ')||'Свежая сводка появится после обновления сервера.'}
function renderInstaller(info={}){$('downloadInstallerBtn').disabled=!info.available;$('installerMeta').textContent=info.available?'Версия '+(info.version||'—')+' · '+(info.size?Math.max(1,Math.round(info.size/1048576))+' МБ':'готов к загрузке'):'Установщик ещё собирается'}
function bindCommands(){document.querySelectorAll('.agent-command').forEach(btn=>btn.onclick=()=>{const run=()=>{btn.disabled=true;api('agents/'+encodeURIComponent(btn.dataset.source)+'/commands',{method:'POST',body:{command:btn.dataset.command,payload:{}}}).then(r=>{btn.disabled=false;toast(r.data?.ok?(btn.dataset.command==='lock'?'Команда Win + L отправлена':'Команда отправлена'):(r.data?.detail||'Ошибка'))}).catch(()=>{btn.disabled=false;toast('Нет связи')})};btn.dataset.command==='lock'?ask('Заблокировать экран '+btn.dataset.source+'? Разблокировка возможна только паролем, PIN или Windows Hello на самом ПК.',ok=>ok&&run()):run()})}
function renderBoot(data){state.boot=data;state.owner=!!data.user?.is_owner;$('appVersion').textContent='XASS '+(data.app_version||'');$('headStatus').textContent='В сети';$('headDot').className='dot ok';$('helloTitle').textContent=(data.user?.first_name?'Привет, '+data.user.first_name+'.':'Система в сети.');$('homeMetrics').innerHTML=metricHtml(data.metrics);$('serverMetrics').innerHTML=metricHtml(data.metrics);$('homeDevices').innerHTML=deviceHtml((data.sources||[]).slice(0,3));$('deviceList').innerHTML=deviceHtml(data.sources||[],true);bindCommands();renderSettings(data.settings);renderMusic(data.status);renderWeather(data.status?.weather);renderInstaller(data.windows_installer||{});$('vkAppId').value=data.vk_app_id||'';$('serviceList').innerHTML=Object.entries(data.services||{}).map(([name,value])=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(name)+'</div></div><span class="status '+(value==='active'?'':'off')+'">'+esc(value)+'</span></div>').join('')||'<div class="empty">Сервисы не настроены.</div>';$('gate').style.display='none';$('app').hidden=false;$('tabs').hidden=false;$('logoutBtn').style.display=state.pwa?'inline-block':'none'}
function loadBoot(){return api('bootstrap').then(r=>{if(r.status!==200||!r.data?.ok)throw new Error(r.data?.detail||'Нет доступа');renderBoot(r.data)}).catch(error=>showDeny(error.message))}
function showDeny(text){$('loader').style.display='none';$('login').style.display='none';$('deny').style.display='block';$('denyText').textContent=text||'Не удалось подключиться.'}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('on',v.id==='view-'+name));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('on',t.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='site'&&!state.site)loadSite();if(name==='tools')loadUpdateStatus()}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view));$('retryBtn').onclick=()=>location.reload();$('refreshBtn').onclick=loadBoot;
function pushSetting(key,value,done){api('setting',{method:'POST',body:{key,value}}).then(r=>{if(!r.data?.ok)return toast(r.data?.detail||'Ошибка');if(r.data.settings){state.boot.settings=r.data.settings;renderSettings(r.data.settings)}if(r.data.status){state.boot.status=r.data.status;renderMusic(r.data.status)}done?.()})}
$('saveModeBtn').onclick=()=>pushSetting('save_mode_cycle',null);$('quietToggle').onclick=()=>pushSetting('quiet_toggle',null);$('awayToggle').onclick=()=>pushSetting('away_toggle',null);$('awaySaveBtn').onclick=()=>pushSetting('away_message',$('awayMessage').value,()=>toast('Автоответ сохранён'));function updateAwayCount(){$('awayCount').textContent=$('awayMessage').value.length+' / 4000'}$('awayMessage').addEventListener('input',updateAwayCount);
document.querySelectorAll('#sourceSeg button').forEach(button=>button.onclick=()=>pushSetting('now_source',button.dataset.source,()=>{renderMusic({...state.boot.status,now_source:button.dataset.source,now_source_label:button.textContent});toast('Источник изменён')}));
async function findMusic(){const q=$('musicInput').value.trim();if(!q)return toast('Введите исполнителя и трек');$('musicBtn').disabled=true;$('musicBtn').textContent='Ищу…';try{const r=await api('music?q='+encodeURIComponent(q));if(!r.data?.ok)throw new Error(r.data?.detail||'Не найдено');const d=r.data;$('musicResult').style.display='block';$('musicTitle').textContent=[d.artist,d.title].filter(Boolean).join(' — ')||d.query;$('musicMeta').textContent=d.album||'Альбом не указан';$('musicArt').src=d.artwork_url||'/assets/xass-app-icon-192.png';$('musicLinks').innerHTML=Object.entries(d.links||{}).map(([label,url])=>'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(label)+' ↗</a>').join('');haptic('medium')}catch(e){toast(e.message)}finally{$('musicBtn').disabled=false;$('musicBtn').textContent='Найти'}}$('musicBtn').onclick=findMusic;$('musicInput').addEventListener('keydown',e=>{if(e.key==='Enter')findMusic()});
$('discordSave').onclick=()=>pushSetting('discord_tag',$('discordTag').value,()=>toast('Discord сохранён'));$('vkSave').onclick=()=>pushSetting('vk_app_id',$('vkAppId').value,()=>toast('VK App ID сохранён'));$('vkConnect').onclick=()=>api('vk-url?chat_id='+(state.boot?.user?.id||'')).then(r=>{if(!r.data?.ok)return toast(r.data?.detail||'Сначала сохраните VK App ID');const url=r.data.url;if(tg?.openLink)tg.openLink(url);else window.open(url,'_blank')});
$('pairBtn').onclick=function(){this.disabled=true;api('agents/pair-code',{method:'POST',body:{server_url:location.origin}}).then(r=>{this.disabled=false;if(!r.data?.ok)return toast(r.data?.detail||'Ошибка');state.connection=r.data.connection;$('pairPanel').style.display='block';$('pairCode').textContent=r.data.code;$('pairServerUrl').value=r.data.server_url||location.origin;$('pairExpiry').textContent='Ключ действует '+r.data.ttl_minutes+' мин'})};function connection(){return state.connection?{...state.connection,server_url:$('pairServerUrl').value.trim(),pair_code:$('pairCode').textContent.trim()}:null}$('downloadPairBtn').onclick=()=>{const p=connection();if(!p)return;const url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='xass-connect.xass';a.click();setTimeout(()=>URL.revokeObjectURL(url),700)};$('copyPairBtn').onclick=()=>{const p=connection();if(!p)return;navigator.clipboard?.writeText('Сервер: '+p.server_url+'\nКлюч: '+p.pair_code);toast('Скопировано')};
$('downloadInstallerBtn').onclick=async function(){if(demo)return toast('Демо: XASS-Setup.exe');this.disabled=true;try{const headers={};if(initData)headers['X-Telegram-Init-Data']=initData;const response=await fetch('/proxy.php?_binary=1&_p='+encodeURIComponent('/api/mini/agent-installer/download'),{headers,credentials:'include'}),status=Number(response.headers.get('X-XASS-Status')||response.status);if(status!==200)throw new Error('HTTP '+status);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=state.boot?.windows_installer?.file_name||'XASS-Setup.exe';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('Установщик скачан')}catch(e){toast('Не удалось скачать установщик')}finally{renderInstaller(state.boot.windows_installer||{})}};
function loadUpdateStatus(){api('update-status').then(r=>{const d=r.data||{};$('updateResult').style.display='block';$('updateResult').textContent=d.has_updates?'Доступно изменений: '+(d.commits||[]).length:'Сервер обновлён';$('runUpdateBtn').disabled=!d.has_updates})}$('checkUpdateBtn').onclick=loadUpdateStatus;$('runUpdateBtn').onclick=function(){this.disabled=true;$('updateResult').style.display='block';$('updateResult').textContent='Устанавливаю обновление…';api('run-update',{method:'POST'}).then(r=>{$('updateResult').textContent=r.data?.ok?'Готово\n'+(r.data.steps||[]).join('\n'):'Ошибка: '+(r.data?.error||r.data?.detail||'нет данных');this.disabled=false}).catch(()=>{$('updateResult').textContent='Связь прервана — сервер перезапускается.';this.disabled=false})};$('restartServerBtn').onclick=()=>ask('Перезапустить backend XASS?',ok=>{if(ok)api('restart',{method:'POST'}).then(()=>toast('Перезапуск запланирован'))});
function loadLogs(){api('logs?limit=30').then(r=>{$('logList').innerHTML=(r.data?.logs||[]).map(x=>'<div class="log"><div class="log-meta"><span>'+esc(x.chat_title||x.from_username||'XASS')+' · '+esc(x.direction||'')+'</span><span>'+(x.date?new Date(x.date).toLocaleString('ru-RU'):'')+'</span></div><div class="log-text">'+esc(x.text||'')+'</div></div>').join('')||'<div class="empty">Сообщений нет.</div>'})}$('logsBtn').onclick=loadLogs;function loadQuotes(){api('quotes').then(r=>{$('quoteList').innerHTML=(r.data?.quotes||[]).map(x=>'<div class="quote"><span>'+esc(x.text)+'</span><button class="btn danger quote-delete" data-id="'+esc(x.id)+'">Удалить</button></div>').join('')||'<div class="empty">Цитат нет.</div>';document.querySelectorAll('.quote-delete').forEach(b=>b.onclick=()=>api('quotes/'+encodeURIComponent(b.dataset.id),{method:'DELETE'}).then(loadQuotes))})}$('quoteAdd').onclick=()=>{const text=$('quoteInput').value.trim();if(!text)return;api('quotes',{method:'POST',body:{text}}).then(r=>{if(r.data?.ok){$('quoteInput').value='';loadQuotes()}})};document.querySelectorAll('.disclosure details')[1].addEventListener('toggle',e=>{if(e.target.open)loadQuotes()});$('copyDiag').onclick=()=>{const b=state.boot||{},safe={app_version:b.app_version,status:b.status,sources:(b.sources||[]).map(x=>({source_name:x.source_name,source_type:x.source_type,is_online:x.is_online,last_seen_at:x.last_seen_at,agent_version:x.agent_version})),metrics:b.metrics,services:b.services};navigator.clipboard?.writeText(JSON.stringify(safe,null,2));toast('Диагностика скопирована')};
function renderSite(data){state.site=data;const p=data.profile||{};for(const [id,key] of [['siteName','name'],['siteUsername','username'],['siteTitle','title'],['siteBio','bio'],['siteTelegram','telegram_url'],['siteAvatar','avatar_url'],['siteQuote','quote']])$(id).value=p[key]||'';$('siteStack').value=(p.stack||[]).join(', ');$('siteLinks').value=(p.links||[]).map(x=>(x.label||'')+' | '+(x.url||'')).join('\n');renderProjects(data.projects||[])}function loadSite(){api('site').then(r=>r.data?.ok?renderSite(r.data):toast(r.data?.detail||'Ошибка сайта'))}function profilePayload(){return{name:$('siteName').value,username:$('siteUsername').value,title:$('siteTitle').value,bio:$('siteBio').value,telegram_url:$('siteTelegram').value,avatar_url:$('siteAvatar').value,quote:$('siteQuote').value,stack:$('siteStack').value.split(',').map(x=>x.trim()).filter(Boolean),links:$('siteLinks').value.split('\n').map(line=>{const parts=line.split('|');return{label:(parts.shift()||'').trim(),url:parts.join('|').trim()}}).filter(x=>x.label&&x.url)}}$('saveProfileBtn').onclick=function(){this.disabled=true;api('site/profile',{method:'POST',body:profilePayload()}).then(r=>{this.disabled=false;r.data?.ok?toast('Профиль сохранён'):toast(r.data?.detail||'Ошибка')})};$('openSiteBtn').onclick=()=>{const url=state.site?.public_url||location.origin+'/profile.php';tg?.openLink?tg.openLink(url):window.open(url,'_blank')};
function renderProjects(list){state.site=state.site||{};state.site.projects=list;$('projectList').innerHTML=list.map(p=>'<div class="project"><div class="project-head"><div><div class="project-name">'+esc(p.title)+'</div><div class="project-desc">'+esc(p.description||p.subtitle||'Без описания')+'</div></div><span class="status">'+esc(p.status||'dev')+'</span></div><div class="device-actions"><button class="btn edit-project" data-id="'+esc(p.id)+'">Изменить</button><button class="btn danger delete-project" data-id="'+esc(p.id)+'">Удалить</button></div></div>').join('')||'<div class="empty">Проектов пока нет.</div>';document.querySelectorAll('.edit-project').forEach(b=>b.onclick=()=>openProject(list.find(p=>p.id===b.dataset.id)||{}));document.querySelectorAll('.delete-project').forEach(b=>b.onclick=()=>ask('Удалить проект?',ok=>ok&&api('site/projects/'+encodeURIComponent(b.dataset.id),{method:'DELETE'}).then(r=>r.data?.ok&&renderProjects(r.data.projects))))}
function openProject(p={}){const y=new Date().getFullYear();$('projectForm').style.display='block';$('projectFormTitle').textContent=p.id?'Редактировать проект':'Новый проект';$('projectId').value=p.id||'';$('projectTitle').value=p.title||'';$('projectStatus').value=p.status||'dev';$('projectSubtitle').value=p.subtitle||'';$('projectDescription').value=p.description||'';$('projectUrl').value=p.url||'';$('projectFrom').value=p.years?.from||y;$('projectTo').value=p.years?.to||y;$('projectTags').value=(p.tags||[]).join(', ');$('projectCover').value=p.cover?.src||'';$('projectFeatured').checked=!!p.featured;$('projectForm').scrollIntoView({behavior:'smooth'})}function projectPayload(){return{id:$('projectId').value,title:$('projectTitle').value,status:$('projectStatus').value,subtitle:$('projectSubtitle').value,description:$('projectDescription').value,url:$('projectUrl').value,year_from:Number($('projectFrom').value),year_to:Number($('projectTo').value),tags:$('projectTags').value.split(',').map(x=>x.trim()).filter(Boolean),cover_type:'image',cover_src:$('projectCover').value,featured:$('projectFeatured').checked}}$('newProjectBtn').onclick=()=>openProject();$('cancelProjectBtn').onclick=()=>{$('projectForm').style.display='none'};$('saveProjectBtn').onclick=function(){if(!$('projectTitle').value.trim())return toast('Введите название');this.disabled=true;api('site/projects',{method:'POST',body:projectPayload()}).then(r=>{this.disabled=false;if(r.data?.ok){renderProjects(r.data.projects);$('projectForm').style.display='none';toast('Проект сохранён')}else toast(r.data?.detail||'Ошибка')})};
$('logoutBtn').onclick=()=>pwaApi('logout',{method:'POST'}).then(()=>location.reload());
async function initPwa(){try{const r=await pwaApi('config');if(r.data?.authenticated)return loadBoot();$('loader').style.display='none';$('login').style.display='block';if(!r.data?.login_ready){$('telegramWidget').innerHTML='<div class="empty">Укажите TELEGRAM_BOT_USERNAME на сервере и привяжите домен через /setdomain в BotFather.</div>';return}window.onTelegramAuth=async user=>{try{const login=await pwaApi('login',{method:'POST',body:user});if(login.status!==200||!login.data?.ok)throw new Error(login.data?.detail||'Вход отклонён');$('login').style.display='none';$('loader').style.display='flex';await loadBoot()}catch(e){toast(e.message)}};const script=document.createElement('script');script.async=true;script.src='https://telegram.org/js/telegram-widget.js?22';script.dataset.telegramLogin=r.data.bot_username;script.dataset.size='large';script.dataset.userpic='false';script.dataset.radius='0';script.dataset.onauth='onTelegramAuth(user)';$('telegramWidget').appendChild(script)}catch(e){showDeny('Backend недоступен: '+e.message)}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
demo||initData?loadBoot():initPwa();
})();
</script>
</body></html>
