<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,maximum-scale=1">
<meta name="theme-color" content="#000000"><meta name="color-scheme" content="dark">
<title>XASS</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
:root{--bg:#000;--surface:#090d12;--surface2:#0d1219;--surface3:#111822;--line:#27303a;--soft:#171d25;--text:#f5f7fb;--muted:#929baa;--blue:#2878ff;--violet:#7457ff;--green:#45d982;--amber:#efb65c;--red:#f36b76;--nav:rgba(3,5,8,.96)}
*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}html{background:var(--bg);scroll-behavior:smooth}body{min-height:100vh;background:var(--bg);color:var(--text);font-family:Manrope,"Segoe UI",sans-serif;font-size:14px;line-height:1.5;padding-bottom:calc(106px + env(safe-area-inset-bottom));overflow-x:hidden}button,input,textarea,select{font:inherit}button{cursor:pointer}.wrap{width:min(720px,100%);margin:0 auto;padding:20px 18px 24px}.app-head{height:86px;display:flex;align-items:center;border-bottom:1px solid var(--line)}.brand{font-size:36px;font-weight:600;letter-spacing:-2.1px}.head-state{margin-left:auto;display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:var(--muted)}.dot.ok{background:var(--green);box-shadow:0 0 0 5px rgba(69,217,130,.08)}.dot.bad{background:var(--red)}.dot.wait{background:var(--amber)}
.view{display:none}.view.on{display:block;animation:enter .24s ease both}@keyframes enter{from{opacity:.25;transform:translateY(6px)}to{opacity:1;transform:none}}.hero-state{width:100%;display:grid;grid-template-columns:48px minmax(0,1fr) 22px;gap:16px;align-items:center;margin:22px 0;border:1px solid #33445a;color:var(--text);text-align:left;background:radial-gradient(circle at 5% 0,rgba(40,120,255,.16),transparent 52%),var(--surface);padding:20px;border-radius:16px}.hero-icon{width:42px;height:42px;color:var(--blue)}.hero-title,.hero-sub{display:block}.hero-title{font-size:20px;font-weight:650}.hero-sub{color:var(--muted);font-size:12px;margin-top:2px}.chev{width:20px;height:20px;color:#dfe5ed}.section{padding:24px 0;border-top:1px solid var(--line)}.section:first-child{border-top:0}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;margin-bottom:14px}.section-title{font-size:21px;line-height:1.15;font-weight:600;letter-spacing:-.03em}.section-note{font-size:11px;color:var(--muted)}
.panel{border:1px solid var(--line);background:linear-gradient(145deg,var(--surface),#06080b);border-radius:16px;overflow:hidden}.metric{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:14px;align-items:center;padding:17px;border-bottom:1px solid var(--line)}.metric:last-child{border-bottom:0}.metric-icon{width:30px;height:30px;color:var(--blue);padding:3px;border:1px solid #314057;border-radius:8px}.metric:nth-child(2) .metric-icon{color:var(--violet)}.metric-name{font-size:15px;font-weight:600}.metric-track{height:5px;background:#20262e;border-radius:99px;margin-top:9px;overflow:hidden}.metric-track span{height:100%;display:block;background:var(--blue);border-radius:inherit;transition:width .35s ease}.metric:nth-child(2) .metric-track span{background:var(--violet)}.metric-value{font-size:17px;font-weight:650;font-variant-numeric:tabular-nums}.device{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:14px;align-items:center;padding:16px;border-bottom:1px solid var(--line)}.device:last-child{border-bottom:0}.device-icon{width:30px;height:30px;color:var(--blue)}.device-name{font-weight:650;font-size:15px}.device-meta{color:var(--muted);font-size:11px;margin-top:3px}.device-state{color:var(--blue);font-size:12px}.device-state.off{color:var(--red)}.device-actions{grid-column:2/4;display:flex;gap:8px;padding-bottom:3px}.now{display:grid;grid-template-columns:42px minmax(0,1fr);gap:14px;align-items:center;padding:18px}.now-icon{width:32px;height:32px;color:var(--violet)}.now-label{font-size:11px;color:var(--muted)}.now-title{font-size:15px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.btn{border:1px solid var(--line);background:var(--surface2);color:var(--text);border-radius:10px;min-height:42px;padding:9px 14px;font-size:12px;font-weight:650;transition:.15s}.btn:active{transform:scale(.98)}.btn.primary{border-color:var(--blue);background:var(--blue);color:white}.btn.outline{border-color:#345fa6;background:transparent;color:#78a9ff}.btn.danger{border-color:rgba(243,107,118,.35);background:rgba(243,107,118,.08);color:#ffabb2}.btn.small{min-height:34px;padding:6px 10px;font-size:11px}.btn:disabled{opacity:.45;cursor:default}.toolbar{display:flex;gap:9px;flex-wrap:wrap}.toolbar .btn{flex:1}.action-row{display:flex;align-items:center;gap:13px;padding:16px;border-bottom:1px solid var(--line)}.action-row:last-child{border-bottom:0}.action-copy{min-width:0;flex:1}.action-title{font-weight:600}.action-sub{font-size:11px;color:var(--muted);margin-top:2px}.surface{border:1px solid var(--line);background:var(--surface);border-radius:14px;padding:16px;margin-top:14px}.surface-title{font-size:16px;font-weight:650}.surface-sub{font-size:11px;color:var(--muted);margin-top:3px}.pair-code{font-family:"Cascadia Mono",Consolas,monospace;font-size:27px;letter-spacing:3px;color:#80adff;margin:16px 0}.mono{font-family:"Cascadia Mono",Consolas,monospace}
.label{display:block;font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;margin:14px 0 6px}.input{width:100%;border:1px solid var(--line);background:var(--surface2);color:var(--text);border-radius:10px;min-height:43px;padding:10px 12px;outline:none}.input:focus{border-color:var(--blue)}textarea.input{min-height:88px;resize:vertical}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form-actions{display:flex;gap:9px;margin-top:16px}.form-actions .btn{flex:1}.toggle{width:48px;height:28px;border:1px solid var(--line);border-radius:99px;background:var(--surface3);position:relative}.toggle:after{content:"";position:absolute;width:22px;height:22px;left:2px;top:2px;border-radius:50%;background:#dce2ea;transition:.2s}.toggle.on{background:var(--blue);border-color:var(--blue)}.toggle.on:after{transform:translateX(20px);background:white}.setting{display:flex;align-items:center;gap:12px;min-height:62px;border-bottom:1px solid var(--line)}.setting:last-child{border-bottom:0}.setting-main{min-width:0;flex:1}.setting-title{font-weight:600}.setting-desc{font-size:11px;color:var(--muted)}
.project-row{padding:16px;border-bottom:1px solid var(--line)}.project-row:last-child{border-bottom:0}.project-top{display:flex;align-items:start;gap:12px}.project-copy{min-width:0;flex:1}.project-title{font-size:16px;font-weight:650}.project-desc{color:var(--muted);font-size:11px;margin-top:4px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.project-status{font-size:10px;color:var(--blue);text-transform:uppercase}.project-actions{display:flex;gap:8px;margin-top:12px}.project-actions .btn{flex:1}.service{display:flex;align-items:center;gap:12px;min-height:54px;padding:0 16px;border-bottom:1px solid var(--line)}.service:last-child{border-bottom:0}.service-name{flex:1}.service-state{color:var(--green);font-size:11px}.log{padding:12px 0;border-bottom:1px solid var(--line)}.log:last-child{border-bottom:0}.log-top{display:flex;gap:8px;color:var(--muted);font-size:10px}.log-title{color:var(--text);font-weight:600}.log-time{margin-left:auto}.log-text{font-size:12px;color:#b4bdc8;margin-top:5px}.empty{color:var(--muted);font-size:12px;padding:16px}.update-result{font-size:11px;white-space:pre-wrap;color:#b7c2d1}.danger-text{color:var(--red)}
.tabs{position:fixed;z-index:30;left:0;right:0;bottom:0;background:var(--nav);border-top:1px solid var(--line);padding:6px 8px calc(6px + env(safe-area-inset-bottom));backdrop-filter:blur(16px)}.tabs-inner{width:min(720px,100%);margin:0 auto;display:grid;grid-template-columns:repeat(4,1fr)}.tab{border:0;background:transparent;color:#747e8d;min-height:62px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:10px;font-weight:600}.tab svg{width:23px;height:23px}.tab.on{color:var(--blue);box-shadow:inset 0 2px 0 var(--blue)}.toast{position:fixed;z-index:60;left:50%;bottom:92px;transform:translate(-50%,14px);opacity:0;pointer-events:none;max-width:90%;background:#151c26;border:1px solid #344152;color:var(--text);border-radius:10px;padding:10px 14px;font-size:12px;transition:.2s}.toast.show{opacity:1;transform:translate(-50%,0)}.loading{position:fixed;z-index:70;inset:0;background:var(--bg);display:flex;align-items:center;justify-content:center;gap:12px;color:var(--muted)}.spinner{width:25px;height:25px;border:2px solid var(--line);border-top-color:var(--blue);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.deny{display:none;text-align:center;padding:100px 28px}.deny h2{font-size:24px;margin-bottom:8px}.deny p{color:var(--muted);margin-bottom:18px}
@media(max-width:430px){.wrap{padding-left:14px;padding-right:14px}.app-head{height:76px}.brand{font-size:32px}.hero-state{padding:17px}.grid2{grid-template-columns:1fr}.section-title{font-size:20px}.metric{padding:15px}.device-actions{grid-column:1/4}.hero-title{font-size:18px}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
</style></head>
<body>
<div class="loading" id="loading"><div class="spinner"></div><span>Подключение к XASS…</span></div><div class="toast" id="toast"></div>
<main class="wrap" id="app" style="display:none">
<header class="app-head"><div class="brand">XASS</div><div class="head-state"><span class="dot wait" id="headDot"></span><span id="headStatus">Подключение</span></div></header>

<section class="view on" id="view-overview">
 <button class="hero-state" data-open="server"><svg class="hero-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg><span><span class="hero-title" id="systemText">Система в сети</span><span class="hero-sub">Все сервисы работают штатно</span></span><svg class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 5 7 7-7 7"/></svg></button>
 <div class="section"><div class="section-head"><h2 class="section-title">Сервер</h2><span class="section-note" id="appVersion">—</span></div><div class="panel" id="overviewMetrics"></div></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Устройства</h2><button class="btn small" data-open="agents">Все устройства</button></div><div class="panel" id="overviewAgents"></div></div>
 <div class="section"><div class="panel now"><svg class="now-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M9 18V5l10-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></svg><div><div class="now-label">Сейчас играет</div><div class="now-title" id="nowPlaying">Ничего не играет</div></div></div></div>
 <div class="section"><button class="hero-state" data-open="site"><svg class="hero-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/></svg><span><span class="hero-title">Редактировать сайт</span><span class="hero-sub">Профиль, ссылки и проекты</span></span><svg class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 5 7 7-7 7"/></svg></button></div>
</section>

<section class="view" id="view-agents"><div class="section"><div class="section-head"><div><h2 class="section-title">Устройства</h2><div class="section-note">ПК и серверные агенты</div></div><button class="btn primary" id="pairBtn">Добавить ПК</button></div><div class="surface" id="pairPanel" style="display:none"><div class="surface-title">Подключение нового ПК</div><div class="surface-sub">Скачайте готовый конфиг или скопируйте адрес и ключ</div><label class="label">Адрес сервера</label><input class="input mono" id="pairServerUrl" inputmode="url"><label class="label">Одноразовый ключ</label><div class="pair-code" id="pairCode">—</div><div class="toolbar"><button class="btn primary" id="downloadPairBtn">Скачать конфиг</button><button class="btn outline" id="copyPairBtn">Скопировать</button></div><div class="section-note" id="pairExpiry" style="margin-top:12px"></div></div><div class="panel" id="agentList"></div></div></section>

<section class="view" id="view-server">
 <div class="section"><div class="section-head"><h2 class="section-title">Сервер</h2><button class="btn small" id="refreshBtn">Обновить</button></div><div class="panel" id="serverMetrics"></div></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Сервисы</h2></div><div class="panel" id="serviceList"></div></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Управление</h2></div><div class="panel"><div class="action-row"><div class="action-copy"><div class="action-title">Обновление XASS</div><div class="action-sub" id="updateSummary">Проверка версии не выполнена</div></div><button class="btn outline" id="checkUpdateBtn">Проверить</button></div><div class="action-row"><div class="action-copy"><div class="action-title">Перезапуск backend</div><div class="action-sub">Ответ будет отправлен до остановки сервиса</div></div><button class="btn danger" id="restartServerBtn">Перезапустить</button></div></div><div class="surface update-result" id="updateResult" style="display:none"></div><button class="btn primary" id="runUpdateBtn" style="display:none;width:100%;margin-top:10px">Установить обновление</button></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Бот</h2></div><div class="panel"><div class="setting"><div class="setting-main"><div class="setting-title">Сохранение сообщений</div><div class="setting-desc" id="saveModeDesc">—</div></div><button class="btn small" id="saveModeBtn">Сменить</button></div><div class="setting"><div class="setting-main"><div class="setting-title">Тихие часы</div><div class="setting-desc" id="quietDesc">—</div></div><button class="toggle" id="quietToggle"></button></div><div class="setting"><div class="setting-main"><div class="setting-title">Режим «Не в сети»</div><div class="setting-desc" id="awayDesc">—</div></div><button class="toggle" id="awayToggle"></button></div></div><textarea class="input" id="awayMessage" placeholder="Текст автоответа" style="margin-top:10px"></textarea><button class="btn outline" id="awaySaveBtn" style="width:100%;margin-top:9px">Сохранить автоответ</button></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Последние события</h2><button class="btn small" id="logsBtn">Обновить</button></div><div id="logList"><div class="empty">Нажмите «Обновить».</div></div></div>
</section>

<section class="view" id="view-site">
 <div class="section"><div class="section-head"><div><h2 class="section-title">Сайт</h2><div class="section-note">Публичная визитка XASS</div></div><button class="btn outline" id="openSiteBtn">Открыть</button></div><div class="surface"><div class="surface-title">Профиль</div><label class="label">Имя</label><input class="input" id="siteName"><label class="label">Главный заголовок</label><input class="input" id="siteTitle"><label class="label">Описание</label><textarea class="input" id="siteBio"></textarea><div class="grid2"><div><label class="label">Username</label><input class="input" id="siteUsername"></div><div><label class="label">Telegram URL</label><input class="input" id="siteTelegram"></div></div><label class="label">Avatar URL</label><input class="input" id="siteAvatar"><label class="label">Цитата</label><textarea class="input" id="siteQuote"></textarea><label class="label">Стек — через запятую</label><textarea class="input" id="siteStack"></textarea><label class="label">Ссылки — Название | URL, каждая с новой строки</label><textarea class="input mono" id="siteLinks"></textarea><button class="btn primary" id="saveProfileBtn" style="width:100%;margin-top:14px">Сохранить профиль</button></div></div>
 <div class="section"><div class="section-head"><h2 class="section-title">Проекты</h2><button class="btn primary" id="newProjectBtn">Добавить</button></div><div class="panel" id="projectList"></div><div class="surface" id="projectForm" style="display:none"><div class="surface-title" id="projectFormTitle">Новый проект</div><input type="hidden" id="projectId"><label class="label">Название</label><input class="input" id="projectTitle"><label class="label">Подзаголовок</label><input class="input" id="projectSubtitle"><label class="label">Описание</label><textarea class="input" id="projectDescription"></textarea><div class="grid2"><div><label class="label">Статус</label><select class="input" id="projectStatus"><option value="working">working</option><option value="stable">stable</option><option value="testing">testing</option><option value="dev">dev</option><option value="unstable">unstable</option><option value="archived">archived</option></select></div><div><label class="label">Ссылка</label><input class="input" id="projectUrl"></div></div><div class="grid2"><div><label class="label">Год начала</label><input class="input" id="projectFrom" inputmode="numeric"></div><div><label class="label">Год окончания</label><input class="input" id="projectTo" inputmode="numeric"></div></div><label class="label">Теги — через запятую</label><input class="input" id="projectTags"><label class="label">Обложка URL</label><input class="input" id="projectCover"><label class="setting" style="margin-top:8px"><span class="setting-main"><span class="setting-title">Показывать первым</span><span class="setting-desc">Главный проект на сайте</span></span><input type="checkbox" id="projectFeatured"></label><div class="form-actions"><button class="btn" id="cancelProjectBtn">Отмена</button><button class="btn primary" id="saveProjectBtn">Сохранить</button></div></div></div>
</section>
</main>
<div class="deny" id="deny"><h2>Нет доступа</h2><p id="denyText">Откройте Mini App через бота XASS.</p><button class="btn outline" id="retryBtn">Повторить</button></div>
<nav class="tabs" id="tabs" style="display:none"><div class="tabs-inner">
<button class="tab on" data-view="overview"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>Обзор</button>
<button class="tab" data-view="agents"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/></svg>Устройства</button>
<button class="tab" data-view="server"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="4" y="3" width="16" height="7" rx="2"/><rect x="4" y="14" width="16" height="7" rx="2"/><path d="M8 6.5h.01M8 17.5h.01"/></svg>Сервер</button>
<button class="tab" data-view="site"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg>Сайт</button>
</div></nav>
<script>
(function(){'use strict';
const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;if(tg){try{tg.ready();tg.expand();tg.setHeaderColor&&tg.setHeaderColor('#000000');tg.setBackgroundColor&&tg.setBackgroundColor('#000000')}catch(e){}}
const initData=tg?tg.initData:'';const localDemo=/^(localhost|127\.0\.0\.1)$/.test(location.hostname)&&new URLSearchParams(location.search).get('demo')==='1';const $=id=>document.getElementById(id);const state={owner:false,boot:null,site:null,connection:null,view:'overview'};let toastTimer;
const DEMO={ok:true,app_version:'0.5.0',user:{id:1,first_name:'Артём',username:'demo',is_owner:true},status:{name:'XASS',title:'Системы, которые остаются живыми.',now_listening:'Kavinsky — Nightcall'},settings:{save_mode:'SAVE_FULL',quiet_enabled:false,away_enabled:false,away_message:'Сейчас не в сети.'},sources:[{source_name:'nePC',source_type:'PC_AGENT',is_online:true,last_seen_at:new Date(Date.now()-9000).toISOString(),agent_version:'0.5.0'},{source_name:'SERVER',source_type:'SERVER_AGENT',is_online:true,last_seen_at:new Date().toISOString(),agent_version:'0.5.0'}],metrics:{cpu_percent:28,ram_used_percent:46,ram_used_gb:7.36,ram_total_gb:16,disk_used_percent:62,disk_used_gb:620,disk_total_gb:1000},services:{nginx:'active',postgresql:'active','serverredus-backend':'active'}};
const DEMO_SITE={ok:true,can_edit:true,public_url:'/profile.php',profile:{name:'XASS',title:'Системы, которые остаются живыми.',bio:'Собираю ботов, сервисы и интерфейсы — от идеи до работающего продакшена.',username:'lucifervalter',telegram_url:'https://t.me/lucifervalter',avatar_url:'',quote:'Делаю сложное спокойным.',stack:['Python','FastAPI','Telegram','Windows'],links:[{label:'GitHub',url:'https://github.com/lucifervalter-a11y'}]},projects:[{id:'xass',title:'XASS',subtitle:'Personal control system',description:'Управление сервером, агентами и публичным сайтом.',url:'https://github.com/lucifervalter-a11y/XASS',status:'working',years:{from:2025,to:2026},tags:['Python','Telegram'],featured:true,cover:{type:'image',src:''}}]};
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}function haptic(kind='light'){try{tg&&tg.HapticFeedback&&tg.HapticFeedback.impactOccurred(kind)}catch(e){}}function ask(message,done){if(tg&&tg.showConfirm){tg.showConfirm(message,done)}else done(confirm(message))}
function demoApi(path,opts={}){let data={ok:true};if(path==='bootstrap')data=structuredClone(DEMO);else if(path==='site')data=structuredClone(DEMO_SITE);else if(path==='site/profile'){Object.assign(DEMO_SITE.profile,JSON.parse(opts.body||'{}'));data={ok:true,profile:DEMO_SITE.profile}}else if(path==='site/projects'){const p=JSON.parse(opts.body||'{}');p.id=p.id||'project-'+Date.now();p.years={from:p.year_from,to:p.year_to};p.cover={type:p.cover_type,src:p.cover_src};const i=DEMO_SITE.projects.findIndex(x=>x.id===p.id);if(i>=0)DEMO_SITE.projects[i]=p;else DEMO_SITE.projects.push(p);data={ok:true,projects:DEMO_SITE.projects,project:p}}else if(path.startsWith('site/projects/')&&opts.method==='DELETE'){DEMO_SITE.projects=DEMO_SITE.projects.filter(x=>x.id!==decodeURIComponent(path.split('/').pop()));data={ok:true,projects:DEMO_SITE.projects}}else if(path==='agents/pair-code')data={ok:true,code:'XASS-2048',ttl_minutes:15,server_url:location.origin,connection:{format:'xass-connect',version:1,server_url:location.origin,pair_code:'XASS-2048',expires_at:new Date(Date.now()+900000).toISOString(),auto_update:true}};else if(path==='update-status')data={ok:true,branch:'main',has_updates:true,current:{short_hash:'c3a6d60'},commits:[{short_hash:'new050',subject:'XASS control center redesign'}]};else if(path==='run-update')data={ok:true,after:{short_hash:'new050'},steps:['fast-forward'],restart_scheduled:true};else if(path==='ping')data={ok:true,app_version:'0.5.0'};else if(path==='logs?limit=12')data={ok:true,logs:[{chat_title:'XASS',direction:'system',text:'Heartbeat получен',date:new Date().toISOString()}]};else if(path.includes('/commands'))data={ok:true,command:{status:'pending'}};return Promise.resolve({status:200,data,raw:JSON.stringify(data)})}
function api(path,opts={}){if(localDemo)return demoApi(path,{...opts,body:typeof opts.body==='string'?opts.body:opts.body?JSON.stringify(opts.body):undefined});opts.headers=opts.headers||{};opts.headers['X-Telegram-Init-Data']=initData;if(opts.body&&typeof opts.body!=='string'){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}return fetch('/proxy.php?_p='+encodeURIComponent('/api/mini/'+path),opts).then(r=>r.json().then(env=>{let data=null;try{data=JSON.parse(env._b||'')}catch(e){}return{status:env._s||r.status,data,raw:env._b||''}}))}
function icon(kind,cls='metric-icon'){const paths={cpu:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5m6-5v5M9 18v5m6-5v5M1 9h5m-5 6h5m12-6h5m-5 6h5"/>',ram:'<rect x="3" y="7" width="18" height="10" rx="2"/><path d="M7 10v4m4-4v4m4-4v4m4-4v4M6 4v3m4-3v3m4-3v3m4-3v3"/>',disk:'<path d="M5 4h14l2 5v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9z"/><path d="M3 10h18M16 17h2"/>',pc:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',server:'<rect x="4" y="3" width="16" height="7" rx="2"/><rect x="4" y="14" width="16" height="7" rx="2"/><path d="M8 6.5h.01M8 17.5h.01"/>'};return'<svg class="'+cls+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">'+(paths[kind]||paths.server)+'</svg>'}
function metricRows(m={}){const rows=[['cpu','CPU',Number(m.cpu_percent)||0,''],['ram','Память',Number(m.ram_used_percent)||0,(m.ram_used_gb&&m.ram_total_gb)?m.ram_used_gb+' / '+m.ram_total_gb+' ГБ':''],['disk','Диск',Number(m.disk_used_percent)||0,(m.disk_used_gb&&m.disk_total_gb)?m.disk_used_gb+' / '+m.disk_total_gb+' ГБ':'']];return rows.map(r=>'<div class="metric">'+icon(r[0])+'<div><div class="metric-name">'+r[1]+'</div><div class="metric-track"><span style="width:'+Math.min(100,r[2])+'%"></span></div></div><div><div class="metric-value">'+Math.round(r[2])+'%</div><div class="section-note">'+esc(r[3])+'</div></div></div>').join('')}
function age(iso){if(!iso)return'никогда';const s=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));return s<60?s+' сек назад':s<3600?Math.floor(s/60)+' мин назад':Math.floor(s/3600)+' ч назад'}
function deviceRows(list,full){return list.map(item=>'<div class="device">'+icon(String(item.source_type).includes('SERVER')?'server':'pc','device-icon')+'<div><div class="device-name">'+esc(item.source_name)+'</div><div class="device-meta">v'+esc(item.agent_version||'0.0.0')+' · '+age(item.last_seen_at)+'</div></div><div class="device-state '+(item.is_online?'':'off')+'">'+(item.is_online?'В сети':'Offline')+'</div>'+(full&&state.owner?'<div class="device-actions"><button class="btn outline small agent-command" data-source="'+esc(item.source_name)+'" data-command="update">Обновить</button><button class="btn small agent-command" data-source="'+esc(item.source_name)+'" data-command="restart">Перезапустить</button></div>':'')+'</div>').join('')||'<div class="empty">Устройства ещё не подключены.</div>'}
function renderSettings(s={}){const modes={SAVE_OFF:'Выключено',SAVE_BASIC:'Базовый',SAVE_FULL:'Полный + медиа',SAVE_PRIVATE_ONLY:'Только личные',SAVE_GROUPS_ONLY:'Только группы'};$('saveModeDesc').textContent=modes[s.save_mode]||s.save_mode||'—';$('quietToggle').classList.toggle('on',!!s.quiet_enabled);$('quietDesc').textContent=s.quiet_enabled?'Включены':'Выключены';$('awayToggle').classList.toggle('on',!!s.away_enabled);$('awayDesc').textContent=s.away_enabled?'Автоответ включён':'Выключен';$('awayMessage').value=s.away_message||''}
function bindAgentButtons(){document.querySelectorAll('.agent-command').forEach(b=>b.onclick=()=>{b.disabled=true;api('agents/'+encodeURIComponent(b.dataset.source)+'/commands',{method:'POST',body:{command:b.dataset.command,payload:{}}}).then(r=>{b.disabled=false;toast(r.data&&r.data.ok?'Команда отправлена':'Ошибка');setTimeout(loadBoot,900)}).catch(()=>{b.disabled=false;toast('Нет связи')})})}
function renderBoot(data){state.boot=data;state.owner=!!data.user?.is_owner;$('appVersion').textContent='v'+(data.app_version||'—');$('headStatus').textContent='В сети';$('headDot').className='dot ok';$('systemText').textContent='Система в сети';$('overviewMetrics').innerHTML=metricRows(data.metrics);$('serverMetrics').innerHTML=metricRows(data.metrics);$('overviewAgents').innerHTML=deviceRows((data.sources||[]).slice(0,2),false);$('agentList').innerHTML=deviceRows(data.sources||[],true);bindAgentButtons();$('nowPlaying').textContent=data.status?.now_listening||'Ничего не играет';$('serviceList').innerHTML=Object.entries(data.services||{}).map(([name,value])=>'<div class="service"><span class="dot '+(value==='active'?'ok':'bad')+'"></span><span class="service-name">'+esc(name)+'</span><span class="service-state">'+esc(value)+'</span></div>').join('')||'<div class="empty">Сервисы не настроены.</div>';renderSettings(data.settings);$('loading').style.display='none';$('app').style.display='block';$('tabs').style.display='block'}
function loadBoot(){return api('bootstrap').then(r=>{if(r.status===200&&r.data?.ok)renderBoot(r.data);else throw new Error(r.data?.detail||'Нет доступа')}).catch(e=>{$('loading').style.display='none';$('app').style.display='none';$('tabs').style.display='none';$('deny').style.display='block';$('denyText').textContent=e.message||'Не удалось подключиться'})}
function showView(name){state.view=name;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('on',v.id==='view-'+name));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('on',t.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='server')loadUpdateStatus();if(name==='site')loadSite()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showView(b.dataset.open));$('retryBtn').onclick=()=>location.reload();$('refreshBtn').onclick=loadBoot;
$('pairBtn').onclick=function(){this.disabled=true;api('agents/pair-code',{method:'POST',body:{server_url:location.origin}}).then(r=>{this.disabled=false;if(!r.data?.ok)return toast(r.data?.detail||'Ошибка');state.connection=r.data.connection;$('pairPanel').style.display='block';$('pairCode').textContent=r.data.code;$('pairServerUrl').value=r.data.server_url||location.origin;$('pairExpiry').textContent='Ключ действует '+r.data.ttl_minutes+' мин';toast('Конфиг готов')})};function connectionProfile(){if(!state.connection)return null;return{...state.connection,server_url:$('pairServerUrl').value.trim(),pair_code:$('pairCode').textContent.trim()}}$('downloadPairBtn').onclick=()=>{const p=connectionProfile();if(!p)return;const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='xass-connect.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Конфиг скачан');haptic('medium')};$('copyPairBtn').onclick=()=>{const p=connectionProfile();if(!p)return;navigator.clipboard&&navigator.clipboard.writeText('Сервер: '+p.server_url+'\nКлюч: '+p.pair_code);toast('Скопировано')};
function pushSetting(key,value,done){api('setting',{method:'POST',body:{key,value}}).then(r=>{if(r.data?.ok){state.boot.settings=r.data.settings;renderSettings(r.data.settings);done&&done()}else toast(r.data?.detail||'Ошибка')})}$('saveModeBtn').onclick=()=>pushSetting('save_mode_cycle',null);$('quietToggle').onclick=()=>pushSetting('quiet_toggle',null);$('awayToggle').onclick=()=>pushSetting('away_toggle',null);$('awaySaveBtn').onclick=()=>pushSetting('away_message',$('awayMessage').value,()=>toast('Автоответ сохранён'));
function loadUpdateStatus(){api('update-status').then(r=>{const d=r.data||{};$('updateSummary').textContent=d.has_updates?'Доступно '+(d.commits||[]).length+' изменений':'Установлена актуальная версия';$('runUpdateBtn').style.display=d.has_updates?'block':'none'})}function waitServer(n=0){if(n>40){$('updateResult').textContent='Сервер запускается дольше обычного. Проверьте ещё раз.';return}setTimeout(()=>api('ping').then(r=>{if(r.status===200&&r.data?.ok){$('updateResult').textContent='Сервер снова в сети · v'+r.data.app_version;toast('Сервер запущен');loadBoot();loadUpdateStatus()}else waitServer(n+1)}).catch(()=>waitServer(n+1)),n<4?500:1000)}$('checkUpdateBtn').onclick=loadUpdateStatus;$('runUpdateBtn').onclick=function(){this.disabled=true;$('updateResult').style.display='block';$('updateResult').textContent='Устанавливаю обновление…';api('run-update',{method:'POST'}).then(r=>{this.disabled=false;const d=r.data||{};$('updateResult').textContent=d.ok?'Обновление применено\n'+(d.steps||[]).join('\n'):'Ошибка: '+(d.error||'нет данных');if(d.restart_scheduled)waitServer()}).catch(()=>{$('updateResult').textContent='Соединение прервано. Жду запуск…';waitServer()})};$('restartServerBtn').onclick=()=>ask('Перезапустить backend XASS?',ok=>{if(!ok)return;$('updateResult').style.display='block';$('updateResult').textContent='Перезапускаю сервер…';api('restart',{method:'POST'}).then(r=>{if(r.data?.restart_scheduled)waitServer()}).catch(()=>waitServer())});
function loadLogs(){api('logs?limit=12').then(r=>{$('logList').innerHTML=(r.data?.logs||[]).map(row=>'<div class="log"><div class="log-top"><span class="log-title">'+esc(row.chat_title||row.from_username||'XASS')+'</span><span>'+esc(row.direction||'')+'</span><span class="log-time">'+(row.date?new Date(row.date).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'')+'</span></div><div class="log-text">'+esc(row.text||'')+'</div></div>').join('')||'<div class="empty">Событий нет.</div>'})}$('logsBtn').onclick=loadLogs;
function renderSite(data){state.site=data;const p=data.profile||{};$('siteName').value=p.name||'';$('siteTitle').value=p.title||'';$('siteBio').value=p.bio||'';$('siteUsername').value=p.username||'';$('siteTelegram').value=p.telegram_url||'';$('siteAvatar').value=p.avatar_url||'';$('siteQuote').value=p.quote||'';$('siteStack').value=(p.stack||[]).join(', ');$('siteLinks').value=(p.links||[]).map(x=>(x.label||'')+' | '+(x.url||'')).join('\n');renderProjects(data.projects||[])}function loadSite(){api('site').then(r=>{if(r.data?.ok)renderSite(r.data);else toast(r.data?.detail||'Не удалось загрузить сайт')})}function profilePayload(){return{name:$('siteName').value,title:$('siteTitle').value,bio:$('siteBio').value,username:$('siteUsername').value,telegram_url:$('siteTelegram').value,avatar_url:$('siteAvatar').value,quote:$('siteQuote').value,stack:$('siteStack').value.split(',').map(x=>x.trim()).filter(Boolean),links:$('siteLinks').value.split('\n').map(line=>{const parts=line.split('|');return{label:(parts.shift()||'').trim(),url:parts.join('|').trim()}}).filter(x=>x.label&&x.url)}}$('saveProfileBtn').onclick=function(){this.disabled=true;api('site/profile',{method:'POST',body:profilePayload()}).then(r=>{this.disabled=false;if(r.data?.ok){state.site.profile=r.data.profile;toast('Профиль сайта сохранён');haptic('medium')}else toast(r.data?.detail||'Ошибка сохранения')}).catch(()=>{this.disabled=false;toast('Нет связи')})};$('openSiteBtn').onclick=()=>{const url=state.site?.public_url||location.origin+'/profile.php';if(tg?.openLink)tg.openLink(url);else window.open(url,'_blank')};
function renderProjects(list){state.site=state.site||{};state.site.projects=list;$('projectList').innerHTML=list.map(p=>'<div class="project-row"><div class="project-top"><div class="project-copy"><div class="project-title">'+esc(p.title)+'</div><div class="project-desc">'+esc(p.description||p.subtitle||'Без описания')+'</div></div><span class="project-status">● '+esc(p.status||'dev')+'</span></div><div class="project-actions"><button class="btn small edit-project" data-id="'+esc(p.id)+'">Изменить</button><button class="btn danger small delete-project" data-id="'+esc(p.id)+'">Удалить</button></div></div>').join('')||'<div class="empty">Проектов пока нет.</div>';document.querySelectorAll('.edit-project').forEach(b=>b.onclick=()=>openProject(list.find(p=>p.id===b.dataset.id)));document.querySelectorAll('.delete-project').forEach(b=>b.onclick=()=>ask('Удалить проект?',ok=>{if(ok)api('site/projects/'+encodeURIComponent(b.dataset.id),{method:'DELETE'}).then(r=>{if(r.data?.ok){renderProjects(r.data.projects);toast('Проект удалён')}})}))}
function openProject(p={}){const y=new Date().getFullYear();$('projectForm').style.display='block';$('projectFormTitle').textContent=p.id?'Редактировать проект':'Новый проект';$('projectId').value=p.id||'';$('projectTitle').value=p.title||'';$('projectSubtitle').value=p.subtitle||'';$('projectDescription').value=p.description||'';$('projectStatus').value=p.status||'dev';$('projectUrl').value=p.url||'';$('projectFrom').value=p.years?.from||y;$('projectTo').value=p.years?.to||y;$('projectTags').value=(p.tags||[]).join(', ');$('projectCover').value=p.cover?.src||'';$('projectFeatured').checked=!!p.featured;$('projectForm').scrollIntoView({behavior:'smooth',block:'start'})}function projectPayload(){return{id:$('projectId').value,title:$('projectTitle').value,subtitle:$('projectSubtitle').value,description:$('projectDescription').value,url:$('projectUrl').value,status:$('projectStatus').value,year_from:Number($('projectFrom').value),year_to:Number($('projectTo').value),tags:$('projectTags').value.split(',').map(x=>x.trim()).filter(Boolean),featured:$('projectFeatured').checked,cover_type:'image',cover_src:$('projectCover').value}}$('newProjectBtn').onclick=()=>openProject();$('cancelProjectBtn').onclick=()=>{$('projectForm').style.display='none'};$('saveProjectBtn').onclick=function(){if(!$('projectTitle').value.trim())return toast('Введите название');this.disabled=true;api('site/projects',{method:'POST',body:projectPayload()}).then(r=>{this.disabled=false;if(r.data?.ok){renderProjects(r.data.projects);$('projectForm').style.display='none';toast('Проект сохранён');haptic('medium')}else toast(r.data?.detail||'Ошибка')}).catch(()=>{this.disabled=false;toast('Нет связи')})};
loadBoot();
})();
</script></body></html>
